/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteSlugRouteImport } from './routes/invite.$slug'
import { Route as authenticatedAppLayoutRouteImport } from './routes/(authenticated)/_appLayout'
import { Route as authenticatedAppLayoutEventsIndexRouteImport } from './routes/(authenticated)/_appLayout/events/index'
import { Route as authenticatedAppLayoutEventsPlannerRouteImport } from './routes/(authenticated)/_appLayout/events/planner'
import { Route as authenticatedAppLayoutEventsInvitesRouteImport } from './routes/(authenticated)/_appLayout/events/invites'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteSlugRoute = InviteSlugRouteImport.update({
  id: '/invite/$slug',
  path: '/invite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAppLayoutRoute = authenticatedAppLayoutRouteImport.update({
  id: '/(authenticated)/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAppLayoutEventsIndexRoute =
  authenticatedAppLayoutEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => authenticatedAppLayoutRoute,
  } as any)
const authenticatedAppLayoutEventsPlannerRoute =
  authenticatedAppLayoutEventsPlannerRouteImport.update({
    id: '/events/planner',
    path: '/events/planner',
    getParentRoute: () => authenticatedAppLayoutRoute,
  } as any)
const authenticatedAppLayoutEventsInvitesRoute =
  authenticatedAppLayoutEventsInvitesRouteImport.update({
    id: '/events/invites',
    path: '/events/invites',
    getParentRoute: () => authenticatedAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/events/invites': typeof authenticatedAppLayoutEventsInvitesRoute
  '/events/planner': typeof authenticatedAppLayoutEventsPlannerRoute
  '/events/': typeof authenticatedAppLayoutEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/events/invites': typeof authenticatedAppLayoutEventsInvitesRoute
  '/events/planner': typeof authenticatedAppLayoutEventsPlannerRoute
  '/events': typeof authenticatedAppLayoutEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/(authenticated)/_appLayout': typeof authenticatedAppLayoutRouteWithChildren
  '/invite/$slug': typeof InviteSlugRoute
  '/(authenticated)/_appLayout/events/invites': typeof authenticatedAppLayoutEventsInvitesRoute
  '/(authenticated)/_appLayout/events/planner': typeof authenticatedAppLayoutEventsPlannerRoute
  '/(authenticated)/_appLayout/events/': typeof authenticatedAppLayoutEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/invite/$slug'
    | '/events/invites'
    | '/events/planner'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/invite/$slug'
    | '/events/invites'
    | '/events/planner'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/(authenticated)/_appLayout'
    | '/invite/$slug'
    | '/(authenticated)/_appLayout/events/invites'
    | '/(authenticated)/_appLayout/events/planner'
    | '/(authenticated)/_appLayout/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  authenticatedAppLayoutRoute: typeof authenticatedAppLayoutRouteWithChildren
  InviteSlugRoute: typeof InviteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$slug': {
      id: '/invite/$slug'
      path: '/invite/$slug'
      fullPath: '/invite/$slug'
      preLoaderRoute: typeof InviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/_appLayout': {
      id: '/(authenticated)/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/_appLayout/events/': {
      id: '/(authenticated)/_appLayout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof authenticatedAppLayoutEventsIndexRouteImport
      parentRoute: typeof authenticatedAppLayoutRoute
    }
    '/(authenticated)/_appLayout/events/planner': {
      id: '/(authenticated)/_appLayout/events/planner'
      path: '/events/planner'
      fullPath: '/events/planner'
      preLoaderRoute: typeof authenticatedAppLayoutEventsPlannerRouteImport
      parentRoute: typeof authenticatedAppLayoutRoute
    }
    '/(authenticated)/_appLayout/events/invites': {
      id: '/(authenticated)/_appLayout/events/invites'
      path: '/events/invites'
      fullPath: '/events/invites'
      preLoaderRoute: typeof authenticatedAppLayoutEventsInvitesRouteImport
      parentRoute: typeof authenticatedAppLayoutRoute
    }
  }
}

interface authenticatedAppLayoutRouteChildren {
  authenticatedAppLayoutEventsInvitesRoute: typeof authenticatedAppLayoutEventsInvitesRoute
  authenticatedAppLayoutEventsPlannerRoute: typeof authenticatedAppLayoutEventsPlannerRoute
  authenticatedAppLayoutEventsIndexRoute: typeof authenticatedAppLayoutEventsIndexRoute
}

const authenticatedAppLayoutRouteChildren: authenticatedAppLayoutRouteChildren =
  {
    authenticatedAppLayoutEventsInvitesRoute:
      authenticatedAppLayoutEventsInvitesRoute,
    authenticatedAppLayoutEventsPlannerRoute:
      authenticatedAppLayoutEventsPlannerRoute,
    authenticatedAppLayoutEventsIndexRoute:
      authenticatedAppLayoutEventsIndexRoute,
  }

const authenticatedAppLayoutRouteWithChildren =
  authenticatedAppLayoutRoute._addFileChildren(
    authenticatedAppLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  authenticatedAppLayoutRoute: authenticatedAppLayoutRouteWithChildren,
  InviteSlugRoute: InviteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
